server:
  port: 9050
spring:
  application:
    name: e-commerce-wallet
  datasource:
    url: jdbc:mysql://101.201.254.128:13306/e_commerce?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: dongruan
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 101.201.254.128 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
eureka:
  client:
    service-url:
      defaultZone: http://39.105.102.179:8888//eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
mybatis:
  mapper-locations: classpath*:mapper/*.xml

value:
  zuul-uri: "http://e-commerce-zuul"


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000