server:
  port: 9000

spring:
  application:
    name: e-commerce-zuul

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://39.105.102.179:8888//eureka

management: #actuator配置
  endpoints:
    web:
      exposure:
        include: 'routes'

zuul:
  routes: #给服务配置路由
    e-commerce-admin:
      path: /admin/**
    e-commerce-basicinfo:
      path: /info/**
    e-commerce-order:
      path: /order/**
    e-commerce-product:
      path: /product/**
    e-commerce-wallet:
      path: /wallet/**

  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤

  host:
    connect-timeout-millis: 60000 #配置路由超时
    socket-timeout-millis: 60000

#  prefix: /proxy #给网关路由添加前缀

#hystrix:
#  command: #用于控制HystrixCommand的行为
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 100000 #配置HystrixCommand执行的超时时间，执行超过该时间会进行服务降级处理
#
#ribbon: #全局配置
#  ConnectTimeout: 6000 #服务请求连接超时时间（毫秒）
#  ReadTimeout: 6000 #服务请求处理超时时间（毫秒）