server:
  port: 9000
service-url:
  admin-service: http://localhost:9010
#  basicInfo-service: http://localhost:9020
#  order-service: http://localhost:9030
#  product-service: http://localhost:9040
#  wallet-service: http://localhost:9050
spring:
  application:
    name: e-commerce-gateway
  cloud:
    gateway:
      routes:
        - id: admin_route #路由的ID
          uri: http://localhost:9010 #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/admin/**
#        - id: path_route #路由的ID
#          uri: ${service-url.basicInfo-service}/{id} #匹配后路由地址
#          predicates: # 断言，路径相匹配的进行路由
#            - Path=/basicInfo/{id}
eureka:
  client:
    service-url:
      defaultZone: http://39.105.102.179:8888//eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
